### ISSUE TITLE
Build with LCG nightlies not working

### ISSUE THREAD

**Issue by vvolkl** [key4hep/EDM4hep#42]
Trying to build with `dev3` fails with the cmake error:

```
~/repo/EDM4hep/build (ddg4_plugin *)$ source /cvmfs/sft.cern.ch/lcg/views/dev3/Thu/x86_64-centos7-gcc8-opt/setup.sh
~/repo/EDM4hep/build (ddg4_plugin *)$ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-centos7/bin/gcc
-- Check for working C compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-centos7/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-centos7/bin/g++
-- Check for working CXX compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-centos7/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Thu/x86_64-centos7-gcc8-opt/cmake/ROOTConfig-targets.cmake:1276 (message):
  The imported target "ROOT::cppyy_backend" references the file

     "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Thu/x86_64-centos7-gcc8-opt/lib/python2.7/site-packages/libcppyy_backend.so"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Thu/x86_64-centos7-gcc8-opt/cmake/ROOTConfig-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Thu/x86_64-centos7-gcc8-opt/cmake/ROOTConfig.cmake:92 (include)
  /cvmfs/sft.cern.ch/lcg/releases/CMake/3.14.3-34449/x86_64-centos7-gcc8-opt/share/cmake-3.14/Modules/CMakeFindDependencyMacro.cmake:48 (find_package)
  /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Thu/x86_64-centos7-gcc8-opt/lib64/cmake/podio/podioConfig.cmake:31 (find_dependency)
  CMakeLists.txt:7 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by andresailer** [comment]
There is something wrong with the ROOT installation pointing to a non-existing file, similar happens for DD4hep builds against dev3 or dev4. See https://github.com/AIDASoft/DD4hep/issues/625

**Comment by andresailer** [comment]
We can set up a similar set of jobs as for dd4hep, different lcg versions, compilers, c++ standards, and some allow_to_fail builds for dev[34] https://github.com/AIDASoft/DD4hep/blob/master/.travis.yml

**Comment by andresailer** [comment]
Ticket regarding the RootConfig error: https://sft.its.cern.ch/jira/browse/SPI-1556

**Comment by andresailer** [comment]
This should be working again (at least the ROOTConfig.cmake part)

**Comment by andresailer** [comment]
Solved?

**Comment by vvolkl** [comment]
I added a CI build using dev3, which is still failing: https://travis-ci.com/github/key4hep/EDM4hep/jobs/380241136#L764  The RootConfig part seems to be fixed, but the pythia version in the nightlies is not compatible with the current delphes plugin.

**Comment by gaede** [comment]
I am working on a PR to make the delphes plugin compatible with the latest Pythia version.

**Comment by vvolkl** [comment]
Thanks @gaede, the newest pythia is working fine now. The current error from the dev3 build seems to be unrelated to edm4hep, I get the same doing

```
source /cvmfs/sft.cern.ch/lcg/views/LCG_97a_FCC_2/x86_64-centos7-gcc8-opt/setup.sh 
ddsim --compactFile $ENV{DD4hepINSTALL}/DDDetectors/compact/SiD.xml -N 2 -G --gun.particle pi+ --outputFile my.root
```
- also using LCG97a. @andresailer is this a  lcg issue or a dd4hep issue?

**Comment by andresailer** [comment]
@vvolkl on lxplus I can fix that ddsim header issue with
```
export ROOT_INCLUDE_PATH=/cvmfs/sft.cern.ch/lcg/views/LCG_97a_FCC_2/x86_64-centos7-gcc8-opt/include/Geant4/:$ROOT_INCLUDE_PATH
```
(the DD4hepINSTALL variable is not exported though, so some other path to the XML needs to be given to fully run.)
The beginning of the error before
```
In file included from G__DDG4 dictionary payload:445:
In file included from /cvmfs/sft.cern.ch/lcg/views/LCG_97a_FCC_2/x86_64-centos7-gcc8-opt/include/DDG4/Geant4Config.h:100:
/cvmfs/sft.cern.ch/lcg/views/LCG_97a_FCC_2/x86_64-centos7-gcc8-opt/include/DDG4/Geant4TrackingAction.h:18:10: fatal error: 'G4VUserTrackInformation.hh' file not found
#include "G4VUserTrackInformation.hh"
```

dev3 builds of dd4hep worked 2 hours ago. https://github.com/AIDASoft/DD4hep/runs/1122835253

The beginning of the error message in edm4hep dev3 is different though.
Nothing about not finding a header file. (Restarted the job now)

**Comment by vvolkl** [comment]
Thanks @andresailer! I'll try to get the ROOT_INCLUDE_PATH updated in the setup script.

**Comment by andresailer** [comment]
So the solution to the current dev3 issue is exporting the path to the Geant4 headers in the ROOT_INCLUDE_PATH
e.g.:
```
export ROOT_INCLUDE_PATH=/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc9-dbg/include/Geant4/:$ROOT_INCLUDE_PATH
```
Not sure why the diagnostics from root is not mentioning this but taking the `strace` from  the failed `ddsim` execution, looking for headers (".*\.h") and then at the last ENOENT
```
...
[pid  1789] open("/usr/local/include/G4VHit.hh", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  1789] open("/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/ROOT/HEAD/x86_64-centos7-gcc8-opt/etc//cling/lib/clang/5.0.0/include/G4VHit.hh", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  1789] open("/usr/include/G4VHit.hh", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
...
```
`G4VHit.hh` isn't ever found. (Otherwise these failed lookups are "normal", but usually the file is eventually found.)

I don't understand why a very similar setup compiling dd4hep on top of dev3 doesn't have this problem. Even though that Geant4 folder isn't in any environment variable either.

**Comment by andresailer** [comment]
https://sft.its.cern.ch/jira/browse/SPI-1744
